"""empty message

Revision ID: da98cf66cf62
Revises: 9db19d929187
Create Date: 2023-06-26 15:24:49.973387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da98cf66cf62'
down_revision = '9db19d929187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=120), nullable=True))
        batch_op.drop_column('website')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('upcoming_shows_count')
        batch_op.drop_column('past_shows')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('upcoming_shows')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upcoming_shows', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_shows', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('website_link')

    op.drop_table('Show')
    # ### end Alembic commands ###
